/*
Public EMMA API

Testing KubernetesClustersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package emma

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/emma-community/emma-go-sdk"
)

func Test_emma_KubernetesClustersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KubernetesClustersAPIService CreateKubernetesCluster", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KubernetesClustersAPI.CreateKubernetesCluster(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesClustersAPIService DeleteKubernetesCluster", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kubernetesId int32

		resp, httpRes, err := apiClient.KubernetesClustersAPI.DeleteKubernetesCluster(context.Background(), kubernetesId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesClustersAPIService EditKubernetesCluster", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kubernetesId int32

		resp, httpRes, err := apiClient.KubernetesClustersAPI.EditKubernetesCluster(context.Background(), kubernetesId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesClustersAPIService GetKubernetesCluster", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kubernetesId int32

		resp, httpRes, err := apiClient.KubernetesClustersAPI.GetKubernetesCluster(context.Background(), kubernetesId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesClustersAPIService GetKubernetesClusters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KubernetesClustersAPI.GetKubernetesClusters(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
