/*
Public EMMA API

**Base URL:** *<u>https://api.emma.ms/external</u>*  This **Infrastructure API** is for managing the cloud infrastructure within a project.  To access the API, enter your project, navigate to **Settings** > **Service Apps**, and create a service application. Select the access level **Read**, **Operate**, or **Manage**.  After creating the service application, copy the **Client ID** and **Client Secret**. Send an API request to the endpoint **_/issue-token** as specified in the **Authentication** section of the API documentation. You will receive access and refresh tokens in the response.  The Bearer access token is a text string, included in the request header, example:  *-H Authorization: Bearer {token}*  Use this token for API requests. The access token will expire in 10 minutes. A new access token may be created using the refresh token (without Client ID and Client Secret).

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emma

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VmStart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmStart{}

// VmStart struct for VmStart
type VmStart struct {
	// Action with a virtual machine
	Action string `json:"action"`
}

type _VmStart VmStart

// NewVmStart instantiates a new VmStart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmStart(action string) *VmStart {
	this := VmStart{}
	this.Action = action
	return &this
}

// NewVmStartWithDefaults instantiates a new VmStart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmStartWithDefaults() *VmStart {
	this := VmStart{}
	return &this
}

// GetAction returns the Action field value
func (o *VmStart) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *VmStart) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *VmStart) SetAction(v string) {
	o.Action = v
}

func (o VmStart) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmStart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *VmStart) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVmStart := _VmStart{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVmStart)

	if err != nil {
		return err
	}

	*o = VmStart(varVmStart)

	return err
}

type NullableVmStart struct {
	value *VmStart
	isSet bool
}

func (v NullableVmStart) Get() *VmStart {
	return v.value
}

func (v *NullableVmStart) Set(val *VmStart) {
	v.value = val
	v.isSet = true
}

func (v NullableVmStart) IsSet() bool {
	return v.isSet
}

func (v *NullableVmStart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmStart(val *VmStart) *NullableVmStart {
	return &NullableVmStart{value: val, isSet: true}
}

func (v NullableVmStart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmStart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
